# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'Swift_WB' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

    pod 'AFNetworking'
    pod 'SDWebImage'
    pod 'SVProgressHUD'

  target 'Swift_WBTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Swift_WBUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
